### PR TITLE
Upgrade Ruby to 2.7

### PR DESCRIPTION
**Pull request by knu**
We need to update Ruby to 2.7 before we can look to update to Ruby 3.x.

~~Currently, Ruby 2.7 builds are so flaky and tests are randomly failing whereas no failures are seen with Ruby 2.6.~~ Solved!

### CODE REVIEW

**Comment by knu** [comment]
https://github.com/huginn/huginn/runs/4672758156
Failures are so random I have no idea what is going on. 🤔

**Comment by knu** [comment]
The test instability reproduced on CircleCI containers, so there has to be something there.  I'll investigate further to figure out.

**Comment by knu** [comment]
super_diff was useful while investigating failing tests, but after experiencing unstable test results, turning it off seems to have fixed the problems.

**Comment by vfonic** [comment]
Hey @knu!

What's the status of this PR?
I'm looking into using this project for scraping some data off the web, but my project uses Ruby 2.7.
Ruby 2.6 is at the EOL: https://www.ruby-lang.org/en/downloads/

**Comment by vfonic** [comment]
Hey @knu!

What's the status of this PR?
I'm looking into using this project for scraping some data off the web, but my project uses Ruby 2.7.
Ruby 2.6 is at the EOL: https://www.ruby-lang.org/en/downloads/

**Comment by knu** [comment]
Now that the test flakiness has been fixed, it's time to merge this!

**Pull request merged**
