### PR TITLE
Add Gmail XOAUTH2 support to ImapFolderAgent

### PR DESCRIPTION
**Pull request by knu**
Google announced that IMAP access to Gmail of G Suite will start to require OAuth2 authentication, dropping support for password based LOGIN authentication using app-specific passwords.
https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html

This affects users of ImapFolderAgent who use it to access their G Suite accounts.  For them to keep using ImapFolderAgent to access their mails, they'll need to enable Gmail API in a GCP project in their G Suite domain, create an OAuth2 app for their Huginn instance and configure Huginn to use the client ID and secret of the created app.  In Huginn, the Services page is where they can authenticate with Google and authorize access to Gmail API.  Once ImapFolderAgent is associated with a Google authenticated service, it can access Gmail using the XOAUTH2 authentication using the obtained access key.

The omniauth-dropbox-oauth2 gem is temporarily disabled because its runtime dependency on the omniauth-oauth2 gem has a version requirement that conflicts with that of the omniauth-google-oauth2 gem 0.8.0. (Older versions do not work because they use obsoleted Legacy People API.)
Unfortunately, [omniauth-dropbox-oauth2](https://github.com/bamorim/omniauth-dropbox-oauth2) is an abandoned project.  We might need to host our own fork of it to update the broken dependency.

### CODE REVIEW

**Comment by knu** [comment]
Related issue: https://github.com/huginn/huginn/issues/2682

**Comment by knu** [comment]
This PR adds Google OAuth2 as a Service for use in ImapFolderAgent.  It can be used by GoogleCalendarPublishAgent and GoogleTranslationAgent in the next step, and by any Google API based agents to come.

**Comment by knu** [comment]
FYI, the turn-off got postponed for the moment.
https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html

I know I have to rebase this PR but I've been struggling with upgrading lots of outdated gems in order to introduce omniauth-google-oauth2.  It's really painful. 😣

**Comment by knu** [comment]
Non-core parts of this PR have been merged to master, so it's finally ready for review!

**Review by dsander — APPROVED** [review]

**Pull request merged**
