### PR TITLE
GitHub notifications

### PR DESCRIPTION
**Pull request by joenas**
Hey there.

I couldn't get the [Github API](https://developer.github.com/v3/activity/notifications/) to work with a simple `WebsiteAgent` so I made this! Hopefully it's straight forward enough.

### CODE REVIEW

**Comment by joenas** [comment]
I noticed a few sloppy things. Will fix asap :)

**Comment by joenas** [comment]
All right then!

**Comment by dsander** [comment]
Hi @joenas,

this looks like a very useful Agent. As Huginn currently does not have many active maintainers, every new Agent adds a maintenance burden on us, even though I love to have more Agents available in Huginn. We currently do not have a clear guideline which Agents can/should be added (#2012), so I would like to ask you for some patience. If you want to make the Agent available for everyone immediately you could create a [Agent Gem](https://github.com/huginn/huginn_agent).

**Comment by joenas** [comment]
That's reasonable! As this isn't **incredibly** useful I'd say a gem makes sense 😊

**Comment by joenas** [comment]
Agent gem done: https://github.com/joenas/huginn_github_notifications_agent
Feel free to have a look 😄

**Comment by cantino** [comment]
Nice!

**Comment by joenas** [comment]
And it works because I just got a notification! :P

**Pull request closed without merging**
