### PR TITLE
Bug fix: restrict IFS to only the read builtin

### PR DESCRIPTION
**Pull request by baip**

### CODE REVIEW

**Comment by dsander** [comment]
@baip Tahnk you for taking care of this! We probably had that `=` splitting bug for a long time.

@jeremybmerrill Could you test if the image `huginnbuilder/huginn-single-process:pr-2413` or `huginnbuilder/huginn:pr-2413` (depending on the type of image you are using at the moment) fixes your problem?

**Comment by jeremybmerrill** [comment]
Thank you both! I will try it on Wednesday; am not working until then.

Jeremy B. Merrill

**Comment by jeremybmerrill** [comment]
Yep, it all appears to work! Thank you both for your help.

**Comment by dsander** [comment]
Great, thanks for testing it

**Pull request merged**
