### PR TITLE
Update manual install docs for Ruby 3.2.2

### PR DESCRIPTION
**Pull request by PeterUpfold**
This commit updates the manual install documentation to reference Ruby 3.2.2 and one new build-time dependency for Ruby on Debian.

### CODE REVIEW

**Review by dsander — APPROVED** [review]
Thanks! Looks good to me (even though I didn't test it myself). On which Debian version did you run the installation?

**Review by knu — APPROVED** [review]

**Comment by PeterUpfold** [comment]
> I'm not absolutely sure if libtool-bin has to be there as an explicit dependency. Does a build fail without it?

A fresh build of Debian 12 Bookworm did not require this explicity.

My previous experience was with a Debian Buster which I upgraded straight to Bookworm, which may have required this.

**Comment by dsander** [comment]
Ok 😄  What do we think about removing `libtool-bin` from the dependencies and see if anyone runs into problems?

**Comment by PeterUpfold** [comment]
@dsander @knu I have updated this pull request in e751d84a5903d912838e5118dc5f9de5f0589683 to remove `libtool-bin`.

**Comment by knu** [comment]
Thank you!

**Pull request merged**
