### PR TITLE
Clarify env file passing

### PR DESCRIPTION
**Pull request by bobbysteel**
Clarify how env file can be passed in

### CODE REVIEW

**Comment by bobbysteel** [comment]
is there any way to change this w/o a delete and recommit? i can't find
that in the UI on Github anywhere strangely

**Comment by knu** [comment]
@bobbysteel That's OK, I could do that for you.

@dsander Does the document change look good to you?

**Comment by bobbysteel** [comment]
thanks

**Comment by knu** [comment]
Merged in 6088eaf2, thanks!

**Pull request closed without merging**
