### PR TITLE
Upgrade to Rails 7.0.1

### PR DESCRIPTION
**Pull request by jjeffers**
Upgrade to Rails 7.0.1:

- [x] Upgrade rails gem
- [x] Upgrade rspec
- [x] upgrade delayed_job
- [x] upgrade spring
- [x] Investigate Rails 7.0 framework defaults

### CODE REVIEW

**Comment by knu** [comment]
Thanks for your effort!  Keep it up and ask me whenever you need help.

**Comment by jjeffers** [comment]
In this PR I've set:
```
# config/application.rb

config.load_defaults 7.0
```
given what @knu mentioned re ActiveStorage, etc.

**Comment by jjeffers** [comment]
@knu anything else that needs to be done here?

**Comment by knu** [comment]
@jjeffers Sorry for the delay!  I haven't had the time to look into this.   Have you been running this on your instance?

**Comment by jjeffers** [comment]
@knu I've been testing the docker images (single-process compose, etc) locally. Not sure I can reasonably test all agents, etc, but stepping through a couple just to see what is working.

**Review by knu — APPROVED** [review]
I'm sorry this has taken so long!  I finally started running my instance with this upgrade to see if it works okay.  So far so good, and if everything continues to run smoothly after a bit more observation, I think I can go ahead and merge it.

**Pull request merged**
