### PR TITLE
update Liquid to the latest version 4.0.3

### PR DESCRIPTION
**Pull request by tortoo**
It's the Liquid version 4.0.2 change log [here](https://github.com/Shopify/liquid/commit/8013df8ca2e25b72260d945f0d6bfb1484a7d04c).

It's the Liquid version 4.0.3 change log [here](https://github.com/Shopify/liquid/commit/f2f467bdbc248e7bf26b4f5e552cfbce6052f811).

It's the PR about Liquid of Shopify updating to 4.0.2 as well as adding the `where` filter [here](https://github.com/Shopify/liquid/pull/1026).

It's the usage about `where` filter [here](https://shopify.github.io/liquid/filters/where/).

It's some discussion about request of `where` filter [here](https://github.com/Shopify/liquid/issues/451).

### CODE REVIEW

**Comment by dsander** [comment]
Nice! Almost there, can you also change `liquid (4.0.0)` to `liquid (4.0.3)` in the `Gemfile.lock`?

**Comment by tortoo** [comment]
@dsander Just changed the file `Gemfile.lock` and it seems to be done.

**Comment by dsander** [comment]
Thank you!

**Comment by tortoo** [comment]
It's my pleasure. 🤗

**Pull request merged**
