### PR TITLE
Allow ShellCommandAgent to pass custom input params

### PR DESCRIPTION
**Pull request by Maroo-b**
feature link: https://github.com/cantino/huginn/issues/1868

- All custom properties are downstreamed to output

### CODE REVIEW

**Comment by cantino** [comment]
Hey @Maroo-b, thanks for contributing this!

Right now it looks like any option or event property that isn't in the default set is passed on in the output Event. I think this could be surprising as a default behavior. Perhaps instead we could either 1) add a `merge` option that only merges the received event with the output event when `true` (and would only affect `receive`, not `check`), or 2)  add a `template` option like the one in the [WebsiteAgent](https://github.com/cantino/huginn/blob/master/app/models/agents/website_agent.rb#L119).

What do you think?

**Comment by Maroo-b** [comment]
Hey @cantino thanks for the review :) 

It seems that adding a `merge` option would be easier for end users. I'll send a commit for the enhancement.

Just asking what's the difference between `receive `and `check `methods ? I didn't notice the difference from the spec file.

**Comment by cantino** [comment]
`receive` is triggered when an event comes in, `check` is triggered on the Agent's schedule, if it has one.

**Comment by Maroo-b** [comment]
@cantino PR updated.

**Pull request closed without merging**
