### PR TITLE
Delete .github/workflows/close_inactive_issues.yml

### PR DESCRIPTION
**Pull request by gingerbeardman**
“Stale Issue Bots” are the scourge of GitHub. A disease that has affected so many projects I use or contribute to.

It blows my mind that some people have made it their life’s work to go around adding these bots to as many repos as possible. Said people seem to like looking at blank issues sections, “out of sight out of mind” for unresolved issues. Let’s sweep it under the carpet and pretend it doesn't exist.

But high percentage of issues are open because they haven't been dealt with!

The reasoning for adding this to Huginn was stated as a large number of unresolved issues would discourage people from contributing. I have not seen any changes in contributions since the issues were started to be deleted. If they were all deleted, people might get the impression that this project is very active with fast response times, timely resolutions to bugs, and so on. So, really there's no right or wrong way here, but it seems that there must be a better way of closing issues that have not been looked at or addressed by contributors.

### CODE REVIEW

**Review by virtadpt — APPROVED** [review]
Fully agreed.  Torch it.

**Comment by gingerbeardman** [comment]
https://github.com/huginn/huginn/issues/3092

**Comment by gingerbeardman** [comment]
Closed but still a problem
- https://github.com/huginn/huginn/issues/3091 
- https://github.com/huginn/huginn/issues/3089

**Review by knu — APPROVED** [review]
OK, let's do this and see how it goes.  I've been so busy that I have little time to spend on this project, but you can feel free to poke me any time.

**Pull request merged**
