### PR TITLE
Use Pirate Weather with the Weather Agent

### PR DESCRIPTION
**Pull request by alexcochran**
Fixes [2732](https://github.com/huginn/huginn/issues/2732) by replacing Dark Sky with Pirate Weather, as suggested by @virtadpt.

Uses [pirate_forecast_weather_ruby](https://github.com/alexcochran/pirate-weather-forecast-ruby) as a drop-in replacement for the existing ForecastIO module provided by Dark Sky.

**NOTE: I couldn't get the coveralls step to pass, [but @cantino mentioned it wasn't due to my changes](https://github.com/huginn/huginn/issues/2732#issuecomment-1718626938). I added it back before opening.**

### CODE REVIEW

**Review by knu — COMMENTED** [review]
Sorry for the delay!  I'm not a user of this agent, but the changes look good to me.

Can you please minimize the changes to the README.md file?  I don't want to see actual content updates with style fixes.  Thank you!

**Comment by alexcochran** [comment]
@knu thanks for reviewing! No problem- I'll fix those formatting bits

**Comment by alexcochran** [comment]
@knu I reset to the previous commit on my branch + only kept the changes to the README under the WeatherAgent section. Please let me know if I need to fix anything else

**Review by knu — APPROVED** [review]
Thanks!  Squashing commits as appropriate would have helped, but I can just choose squash-merge.

**Comment by alexcochran** [comment]
> Thanks! Squashing commits as appropriate would have helped, but I can just choose squash-merge.

That's a good point. Thank you for the reminder to do that in future PRs.

**Comment by cantino** [comment]
❤️

**Pull request merged**
