### PR TITLE
Upgrade rubies to the latest minor releases

### PR DESCRIPTION
**Pull request by knu**
The latest teeny versions are 2.6.5, 2.5.7 and 2.4.9.

### CODE REVIEW

**Comment by knu** [comment]
Is Travis doing a good job in maintaining Ruby versions these days?  I’ve had enough of bad experiences in how they did not update the version list in a timely manner. 😵

**Comment by dsander** [comment]
That I don't know, I thought that requesting version `2.6.x` would only work if it also corresponds to the latest version one would get with `2.6`. If that's not the case it's probably better to keep the explicit version numbers.

**Comment by knu** [comment]
Here's an ongoing (at the time of writing) Travis build when configured with teeny parts omitted: https://travis-ci.org/huginn/huginn/builds/620146206

It's being built with rubies 2.6.3, 2.5.5 and 2.4.6. ☹️

**Comment by dsander** [comment]
Damn, I was so happy when I saw this used in a different project. Thanks for doing the research!

**Pull request merged**
