### PR TITLE
Update JsonPath to latest version.

### PR DESCRIPTION
**Pull request by Skarlso**
Hello nice folks of Huginn.

I present to you a JsonPath which does not have Eval in it. You can still pass in the parameter `:allow_eval` it won't break, but it's no longer needed nor used.

JsonPath can now be invoked in whatever way, without a security risk being involved.

### CODE REVIEW

**Comment by Skarlso** [comment]
Ops. So... this test is obsolete.

```ruby
    it "does not eval" do
      expect {
        Utils.value_at({ :foo => 2 }, "foo[?(@ > 1)]")
      }.to raise_error(RuntimeError, /Cannot use .*? eval/)
    end
```

Should I remove it?

**Comment by Skarlso** [comment]
Thanks very much @dsander! :-) yeah I would appreciate a manual test drive. Just to be on the safe side. :-)

**Comment by Skarlso** [comment]
Added a patch version as I found a bug when it was returning the immediate item, and it was trying to access .first on a string for example. I added a unit test and the fix.

**Comment by Skarlso** [comment]
Ups. Wrong merge...

**Comment by dsander** [comment]
@Skarlso  Thanks for updating the PR.
@knu Any objections on merging this?

**Comment by Skarlso** [comment]
Np. :-)

**Comment by Skarlso** [comment]
Thanks very much @knu!

**Comment by dsander** [comment]
Great, thanks again @Skarlso

**Comment by Skarlso** [comment]
Thanks guys. :-)🔝

**Pull request merged**
