### PR TITLE
Fix "already retweeted" error detection

### PR DESCRIPTION
**Pull request by knu**
cf. sferik/twitter#890

### CODE REVIEW

**Comment by knu** [comment]
The twitter gem no longer seems to keep a concise list of changes between versions, so I'll look into the history and fix the build failures.

**Comment by dsander** [comment]
That's a bummer, can you ping me when CI is working? I don't know why but somehow I don't get notifications when new commits are added to a subscribed PR .

**Comment by knu** [comment]
I don't have enough time to dig into the twitter gem updates from 5 to 6, so I'm removing the bundle update part.

**Comment by knu** [comment]
@dsander My PR above has successfully been merged into the upstream, but there hasn't been a new release yet.  I'll revisit and try to update the gem after a new release rolls out.

**Pull request merged**
