### PR TITLE
Change docker image namespace

### PR DESCRIPTION
**Pull request by dsander**
For now we keep pushing to the old namespace but add a warning to users a chance to change their images to the new namespace.

After a few weeks/months we could change the `cantino/huginn*` to a dummy webserver which serves a static page pointing the user to the new image or simply remove them.

### CODE REVIEW

**Comment by cantino** [comment]
Nice, thanks @dsander! The code looks good; I haven't tested the display in Docker.

**Comment by dsander** [comment]
Sorry I meant to attach a screenshot:
screenshot 2017-05-17 10 47 16

**Comment by cantino** [comment]
Nice

**Comment by dsander** [comment]
Thanks, I actually forgot to enable the new images in the build matrix but we should be good now 😄

**Pull request merged**
