### PR TITLE
PeakDetectorAgent: add configurable search_url #1552

### PR DESCRIPTION
**Pull request by movstox**
Let me know if it is still relevant. Submitting for initial feedback.

### CODE REVIEW

**Comment by knu** [comment]
Nice improvement!

**Comment by movstox** [comment]
@knu does it look better? (see last commit)

**Comment by knu** [comment]
@movstox Yes, but the option is still required by validate_options(), meaning existing agents will be treated invalid.  Could you please do these?

- [ ] Document the default value and that a custom value needs `%{q}` in it
- [ ] Remove the `search_url` option from `default_options`
- [ ] Allow `search_url` to be blank

**Comment by movstox** [comment]
@knu got it, submitted an update.

**Comment by knu** [comment]
It now looks fine!  As for `search_url`, I prefer the [URI Template](https://tools.ietf.org/html/rfc6570) to the ruby specific (python flavored) printf() format specifier considering the former has a validatable syntax and `%` is a special character in URI syntax, so I think I'll adopt it if there's no objection.

**Comment by dsander** [comment]
@knu Sure, I don't feel strongly.

**Comment by cantino** [comment]
Nice, thanks @movstox!

**Pull request merged**
