### PR TITLE
Update jsonpath to 0.9.4

### PR DESCRIPTION
**Pull request by Skarlso**
Hello nice folks of Huginn. It's been a while. :) 

I fixed a lot of things since 0.8.3. Replaced eval completely now with the parser and since then, the parser has been tested throughout. A lot of fixes and feature went in for the parser making it a better replacement for the unsafe eval. 

Deleting elements was never working quiet well and the ability was added to delete elements via path, not just index. Also, boolean filters and root elements weren't properly handled. Returning nil for empty elements is now also supported.

Plus general test coverage was also increased.

Enjoy. :)

### CODE REVIEW

**Comment by Skarlso** [comment]
Ups, looks like I left out some dependencies.

**Comment by dsander** [comment]
Awesome, thanks for maintaining the gem! Do you know of any backwards incompatibilities or should everything work as before?

**Comment by Skarlso** [comment]
Hey @dsander. Everything should work as before. The extensive test suit should take care of that. The tests are passing and I have not touched them going backwards. :) 

As always, if anything should arise though, please don't hesitate to tell me, I'll fix it ASAP.

**Comment by dsander** [comment]
Perfect! Not having to eval anymore is great news.

**Comment by Skarlso** [comment]
Indeed! That was one of my main goals. :) To make jsonpath safe. :)

**Pull request merged**
