### PR TITLE
Remove jsonpathv2 as the original is now up-to-date.

### PR DESCRIPTION
**Pull request by Skarlso**
I didn't want to update everything in the Gemlock just what's needed. So I did a `bundle update jsonpathv2` instead of a full bundle update. Is that okay? Or should I update everything? :)

### CODE REVIEW

**Comment by Skarlso** [comment]
joshbuddy/jsonpath#45

**Comment by cantino** [comment]
Yup, that looks right. I think `bundle update jsonpathv2 jsonpath` would also work. Should this change any functional behavior in Huginn?

**Comment by Skarlso** [comment]
Hey man. 

It should not affect huginn at all. It has all the same stuff mine had. And some new fixes even. 

I have not modified core features or the usage methodology. :-)

**Comment by dsander** [comment]
@Skarlso Nice, thanks for working on the `jsonpath` gem(s)!

**Comment by cantino** [comment]
Thanks @Skarlso!

**Pull request merged**
